name: wushouhe
age: 10
hobby:
    - swing
    - run
    - clime
#httpurl: https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&srcqid=574123752488718887&tn=94971219_hao_pg&wd=java%20%E6%B3%9B%E5%9E%8B&oq=%E6%B3%9B%E5%9E%8B&rsv_pq=82b89b5b0000b716&rsv_t=b4feZYYBgzjZJh9E0H8eHrQ8orlbqOlPqXX9x0Y4H6%2FrweXF95VACCuzEDYClrgIUYEvf9GT&rqlang=cn&rsv_enter=1&rsv_sug3=7&rsv_sug1=7&rsv_sug7=100&rsv_sug2=0&inputT=16726&rsv_sug4=16727